In [5]:
%load_ext autoreload
%autoreload
import scrapfin as scf
import pandas as pd
import asyncio
from functools import partial
from IPython.core.debugger import set_trace

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [6]:
scf.yahoo('ACWI','SPY','MTUM', start='2019-01-01', what='adjclose')

C:\Users\Sejin\Anaconda3\lib\site-packages\yahoo_fin\stock_info.py:82: FutureWarning: 'date' is both an index level and a column label.
Defaulting to column, but this will raise an ambiguity error in a future version
  result = result.sort_values("date")

                 ACWI         SPY        MTUM
date
2019-01-02  64.139999  250.179993   99.559998
2019-01-03  63.049999  244.210007   96.809998
2019-01-04  65.059998  252.389999  100.050003
2019-01-07  65.459999  254.380005  101.010002
2019-01-08  65.940002  256.769989  102.260002
2019-01-09  66.550003  257.970001  102.860001
2019-01-10  66.860001  258.880005  103.000000
2019-01-11  66.620003  258.980011  103.070000
2019-01-14  66.239998  257.399994  102.169998
2019-01-15  66.839996  260.350006  103.779999
2019-01-16  67.029999  260.980011  103.620003
2019-01-17  67.519997  262.959991  104.410004
2019-01-18  68.230003  266.459991  105.510002
2019-01-22  67.330002  262.859985  104.349998
2019-01-23  67.500000  263.410004  104.669998
2019-01-24  67.620003  263.549988  104.360001
2019-01-25  68.370003  265.779999  105.040001
2019-01-28  67.900002  263.760010  103.989998
2019-01-29  67.910004  263.410004  103.559998
2019-01-30  68.245003  264.966614  104.569901

In [8]:
alloc = scf.etfdb_alloc('ACWI','SPY','QUAL'); alloc

HBox(children=(IntProgress(value=0, max=3), HTML(value='')))

                                        ACWI    SPY   QUAL
Asset       Common equity              98.05  99.92  99.69
            ETF Cash Component          1.27   0.08   0.31
            Preferred stock             0.68   0.00   0.00
Country     Argentina                   0.03   0.00   0.00
            Australia                   2.14   0.00   0.00
            Austria                     0.08   0.00   0.00
            Belgium                     0.31   0.00   0.00
            Brazil                      0.80   0.00   0.00
            Canada                      3.09   0.00   0.00
            Chile                       0.11   0.00   0.00
            China                       3.41   0.00   0.00
            Colombia                    0.05   0.00   0.00
            Czech Republic              0.02   0.00   0.00
            Denmark                     0.56   0.00   0.00
            Egypt                       0.01   0.00   0.00
            Finland                     0.42   0.00   0.00
            France                      3.04   0.00   0.00
            Germany                     2.76   0.00   0.00
            Greece                      0.02   0.00   0.00
            Hong Kong                   1.05   0.00   0.00
            Hungary                     0.05   0.00   0.00
            India                       0.91   0.00   0.00
            Indonesia                   0.20   0.00   0.00
            Ireland                     0.71   0.94   1.53
            Israel                      0.16   0.00   0.00
            Italy                       0.67   0.00   0.00
            Japan                       7.14   0.00   0.00
            Liechtenstein               0.01   0.00   0.00
            Luxembourg                  0.08   0.00   0.00
            Malaysia                    0.25   0.00   0.00
...                                      ...    ...    ...
Market Cap  Large cap                  89.74  91.72  90.00
            Micro cap                   0.01   0.00   0.00
            Mid cap                     8.62   8.10   9.69
            Small cap                   0.36   0.10   0.00
            Unknown                     0.00   0.00   0.00
Market Tier Developed Markets (ex-US)  36.37   1.90   3.25
            Emerging Markets            9.21   0.00   0.00
            Frontier Markets            0.03   0.00   0.00
            Not-designated              0.01   0.00   0.00
            United States              54.37  98.10  96.75
Region      Africa                      0.77   0.00   0.00
            Asia                        7.93   0.00   0.00
            Asia-Pacific               10.92   0.00   0.00
            Europe                     21.27   1.90   3.25
            Latin America               1.30   0.00   0.00
            Middle East                 0.37   0.00   0.00
            North America              57.46  98.10  96.75
Sector      Basic Materials             4.32   2.32   2.67
            Communications              8.88  10.15  10.30
            Consumer, Cyclical         10.03   9.72   9.07
            Consumer, Non-Cyclical      8.03   7.17   6.61
            ETF Cash Component          1.27   0.08   0.31
            Energy                      6.20   5.46   5.35
            Financials                 17.13  13.74  13.73
            Healthcare                 11.58  14.67  15.18
            Industrials                 9.92   9.38   9.10
            Other                       1.94   1.73   1.36
            Real Estate                 3.06   3.03   3.03
            Technology                 14.44  19.48  20.12
            Utilities                   3.19   3.09   3.19

[85 rows x 3 columns]